# Generated by Django 3.1.2 on 2020-10-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('population', models.IntegerField(null=True, verbose_name='Population')),
                ('gdp', models.FloatField(null=True, verbose_name='GDP')),
                ('currency', models.CharField(max_length=5, null=True, verbose_name='Currency')),
                ('healthcare_budget', models.FloatField(null=True, verbose_name='Healthcare budget')),
                ('healthcare_gdp_pc', models.FloatField(null=True, verbose_name='% of GDP to healthcare')),
                ('covid_cases_total', models.IntegerField(null=True, verbose_name='Total COVID-19 cases')),
                ('covid_deaths_total', models.IntegerField(null=True, verbose_name='Total deaths by Covid-19')),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
    ]
