# Generated by Django 3.1.2 on 2020-12-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("country", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="country_code_alpha_2",
            field=models.CharField(max_length=2, null=True, verbose_name="Country code alpha-2"),
        ),
    ]
