# Generated by Django 3.1.2 on 2020-10-23 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=250)),
                ('procurement_method', models.CharField(choices=[('open', 'Open'), ('limited', 'limited'), ('direct', 'direct'), ('selective', 'selective')], max_length=25)),
                ('supplier_name', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('active', 'active'), ('completed', 'completed'), ('canceled', 'canceled')], max_length=25)),
                ('value_usd', models.FloatField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.country')),
            ],
        ),
    ]
