# Generated by Django 3.1.2 on 2020-12-03 06:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_auto_20201203_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.CharField(default='', max_length=10, verbose_name='Country code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='country_code_alpha_2',
            field=models.CharField(default='', max_length=2, verbose_name='Country code alpha-2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='covid19_preparedness',
            field=models.TextField(blank=True, null=True, verbose_name='COVID-19 Preparedness'),
        ),
        migrations.AlterField(
            model_name='country',
            name='covid19_procurement_policy',
            field=models.TextField(blank=True, null=True, verbose_name='COVID-19 Procurement Policy'),
        ),
        migrations.AlterField(
            model_name='country',
            name='covid_cases_total',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total COVID-19 cases'),
        ),
        migrations.AlterField(
            model_name='country',
            name='covid_data_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='covid_deaths_total',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total deaths by Covid-19'),
        ),
        migrations.AlterField(
            model_name='country',
            name='currency',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='country',
            name='equity_age_dist_0_14',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Age distribution 0-14 years'),
        ),
        migrations.AlterField(
            model_name='country',
            name='equity_age_dist_15_24',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Age distribution 15-24 years'),
        ),
        migrations.AlterField(
            model_name='country',
            name='equity_age_dist_25_54',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Age distribution 25-54 years'),
        ),
        migrations.AlterField(
            model_name='country',
            name='equity_age_dist_55_64',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Age distribution 55-64 years'),
        ),
        migrations.AlterField(
            model_name='country',
            name='equity_age_dist_65_above',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Age distribution 65-above years'),
        ),
        migrations.AlterField(
            model_name='country',
            name='equity_gender_dist_female',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Gender distribution female'),
        ),
        migrations.AlterField(
            model_name='country',
            name='equity_gender_dist_male',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Gender distribution male'),
        ),
        migrations.AlterField(
            model_name='country',
            name='equity_income_avg',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Average income'),
        ),
        migrations.AlterField(
            model_name='country',
            name='equity_unemployment_rate',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Unemployment rate'),
        ),
        migrations.AlterField(
            model_name='country',
            name='gdp',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='GDP'),
        ),
        migrations.AlterField(
            model_name='country',
            name='healthcare_budget',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Healthcare budget'),
        ),
        migrations.AlterField(
            model_name='country',
            name='healthcare_gdp_pc',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% of GDP to healthcare'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$', 'Only letters and spaces are allowed in the Country Name')], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Population'),
        ),
        migrations.AlterField(
            model_name='country',
            name='procurement_annual_public_spending',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Annual public procurement spending'),
        ),
        migrations.AlterField(
            model_name='country',
            name='procurement_covid_spending',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='COVID-19 spending'),
        ),
        migrations.AlterField(
            model_name='country',
            name='procurement_gdp_pc',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% of Procurement to GDP'),
        ),
        migrations.AlterField(
            model_name='country',
            name='procurement_total_market_pc',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% from total procurement market'),
        ),
    ]
