# Generated by Django 3.1.2 on 2020-10-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_tender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='procurement_method',
            field=models.CharField(choices=[('open', 'open'), ('limited', 'limited'), ('direct', 'direct'), ('selective', 'selective')], max_length=25),
        ),
    ]
