# Generated by Django 3.1.2 on 2020-12-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_auto_20201203_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='currency',
            field=models.CharField(default='', max_length=50, verbose_name='Currency'),
            preserve_default=False,
        ),
    ]
