# Generated by Django 3.1.2 on 2020-10-23 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_auto_20201023_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to='country.country'),
        ),
    ]
