# Generated by Django 3.1.2 on 2020-12-10 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("country", "0006_tender_no_of_bidders"),
    ]

    operations = [
        migrations.CreateModel(
            name="Buyer",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("buyer_id", models.CharField(max_length=50, verbose_name="Buyer ID")),
                ("buyer_name", models.CharField(blank=True, max_length=250, null=True, verbose_name="Buyer name")),
                (
                    "buyer_address",
                    models.CharField(blank=True, max_length=250, null=True, verbose_name="Buyer address"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoodsServicesCategory",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category_name", models.CharField(max_length=50, unique=True, verbose_name="Category name")),
                ("category_desc", models.TextField(blank=True, null=True, verbose_name="Category description")),
            ],
        ),
        migrations.AddField(
            model_name="supplier",
            name="supplier_address",
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name="Supplier address"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="supplier_id",
            field=models.CharField(default="NULL", max_length=50, verbose_name="Supplier ID"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="supplier",
            name="supplier_name",
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name="Supplier name"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="contract_desc",
            field=models.TextField(blank=True, null=True, verbose_name="Contract description"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="contract_title",
            field=models.TextField(blank=True, null=True, verbose_name="Contract title"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="contract_value_local",
            field=models.FloatField(blank=True, null=True, verbose_name="Contract value local"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="contract_value_usd",
            field=models.FloatField(blank=True, null=True, verbose_name="Contract value USD"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="data_source",
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name="Data source"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="link_to_contract",
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name="Link to contract"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="link_to_tender",
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name="Link to tender"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenders",
                to="country.supplier",
            ),
        ),
        migrations.CreateModel(
            name="GoodsServices",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "classification_code",
                    models.CharField(blank=True, max_length=25, null=True, verbose_name="Classification code"),
                ),
                ("no_of_bidders", models.BigIntegerField(blank=True, null=True, verbose_name="Number of bidders")),
                ("contract_title", models.TextField(blank=True, null=True, verbose_name="Contract title")),
                ("contract_desc", models.TextField(blank=True, null=True, verbose_name="Contract description")),
                ("tender_value_local", models.FloatField(blank=True, null=True, verbose_name="Tender value local")),
                ("tender_value_usd", models.FloatField(blank=True, null=True, verbose_name="Tender value USD")),
                ("award_value_local", models.FloatField(blank=True, null=True, verbose_name="Award value local")),
                ("award_value_usd", models.FloatField(blank=True, null=True, verbose_name="Award value USD")),
                (
                    "contract_value_local",
                    models.FloatField(blank=True, null=True, verbose_name="Contract value local"),
                ),
                ("contract_value_usd", models.FloatField(blank=True, null=True, verbose_name="Contract value USD")),
                (
                    "contract",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goods_services",
                        to="country.tender",
                    ),
                ),
                (
                    "goods_services_category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goods_services",
                        to="country.goodsservicescategory",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tender",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenders",
                to="country.buyer",
            ),
        ),
    ]
