# Generated by Django 3.1.2 on 2020-11-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0006_auto_20201023_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_code',
            field=models.CharField(max_length=10, null=True, verbose_name='Country code'),
        ),
        migrations.AddField(
            model_name='country',
            name='covid_data_last_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='currency',
            field=models.CharField(max_length=50, null=True, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.BigIntegerField(null=True, verbose_name='Population'),
        ),
    ]
