# Generated by Django 3.1.2 on 2020-12-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("country", "0007_auto_20201210_0849"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="buyer_id",
            field=models.CharField(max_length=50, unique=True, verbose_name="Buyer ID"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="supplier_id",
            field=models.CharField(max_length=50, unique=True, verbose_name="Supplier ID"),
        ),
    ]
