# Generated by Django 3.1.2 on 2020-12-10 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("country", "0008_auto_20201210_0906"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsservices",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goods_services",
                to="country.country",
            ),
        ),
    ]
