# Generated by Django 3.1.2 on 2020-12-11 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("country", "0009_goodsservices_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="CovidMonthlyActiveCases",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("covid_data_date", models.DateField()),
                (
                    "active_cases_count",
                    models.BigIntegerField(blank=True, null=True, verbose_name="Active cases count"),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="covid_monthly_active_cases",
                        to="country.country",
                    ),
                ),
            ],
        ),
    ]
