# Generated by Django 3.1.2 on 2021-01-05 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("country", "0014_countrypartner"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CountryPartner",
        ),
    ]
