# Generated by Django 3.1.2 on 2021-01-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0015_delete_countrypartner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='equity_category',
            field=models.ManyToManyField(to='country.EquityCategory'),
        ),
    ]
