# Generated by Django 3.1.2 on 2021-02-15 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("country", "0019_auto_20210205_0823"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("import_type", models.CharField(max_length=150, verbose_name="Import Type")),
                ("description", models.CharField(max_length=500, verbose_name="Description")),
                (
                    "country",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_batch_country",
                        to="country.country",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TempDataImportTable",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("contract_id", models.CharField(max_length=150, null=True, verbose_name="Contract Id")),
                ("contract_date", models.CharField(max_length=150, null=True, verbose_name="Contract date")),
                (
                    "procurement_procedure",
                    models.CharField(max_length=150, null=True, verbose_name="Procurement procedure"),
                ),
                (
                    "procurement_process",
                    models.CharField(max_length=150, null=True, verbose_name="Procurement process"),
                ),
                ("goods_services", models.CharField(max_length=150, null=True, verbose_name="Goods/Services")),
                ("cpv_code_clear", models.CharField(max_length=150, null=True, verbose_name="CPV code clear")),
                ("quantity_units", models.CharField(max_length=150, null=True, verbose_name="Quantity,units")),
                (
                    "ppu_including_vat",
                    models.CharField(max_length=150, null=True, verbose_name="Price per units including VAT"),
                ),
                ("tender_value", models.CharField(max_length=150, null=True, verbose_name="Tender value")),
                ("award_value", models.CharField(max_length=150, null=True, verbose_name="Award value")),
                ("contract_value", models.CharField(max_length=150, null=True, verbose_name="Contract value")),
                ("contract_title", models.CharField(max_length=150, null=True, verbose_name="Contract title")),
                ("contract_description", models.CharField(max_length=150, null=True, verbose_name="Award value")),
                ("no_of_bidders", models.CharField(max_length=150, null=True, verbose_name="No of bidders")),
                ("buyer", models.CharField(max_length=150, null=True, verbose_name="Buyer")),
                ("buyer_id", models.CharField(max_length=150, null=True, verbose_name="Buyer ID")),
                (
                    "buyer_address_as_an_object",
                    models.CharField(max_length=150, null=True, verbose_name="Buyer Address(as an object)"),
                ),
                ("supplier", models.CharField(max_length=150, null=True, verbose_name="Supplier")),
                ("supplier_id", models.CharField(max_length=150, null=True, verbose_name="Supplier ID")),
                ("supplier_address", models.CharField(max_length=150, null=True, verbose_name="Supplier Address")),
                ("contract_status", models.CharField(max_length=150, null=True, verbose_name="Contract Status")),
                (
                    "contract_status_code",
                    models.CharField(max_length=150, null=True, verbose_name="Contract Status Code"),
                ),
                ("link_to_contract", models.CharField(max_length=150, null=True, verbose_name="Link to Contract")),
                ("link_to_tender", models.CharField(max_length=150, null=True, verbose_name="Link to Tender")),
                ("data_source", models.CharField(max_length=150, null=True, verbose_name="Data Source")),
                (
                    "import_batch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_batch",
                        to="country.importbatch",
                    ),
                ),
            ],
        ),
    ]
