# Generated by Django 3.1.2 on 2021-02-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0020_importbatch_tempdataimporttable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempdataimporttable',
            name='award_value',
            field=models.CharField(max_length=1500, null=True, verbose_name='Award value'),
        ),
        migrations.AlterField(
            model_name='tempdataimporttable',
            name='buyer',
            field=models.CharField(max_length=1500, null=True, verbose_name='Buyer'),
        ),
        migrations.AlterField(
            model_name='tempdataimporttable',
            name='buyer_address_as_an_object',
            field=models.CharField(max_length=1500, null=True, verbose_name='Buyer Address(as an object)'),
        ),
        migrations.AlterField(
            model_name='tempdataimporttable',
            name='contract_date',
            field=models.CharField(max_length=1500, null=True, verbose_name='Contract date'),
        ),
        migrations.AlterField(
            model_name='tempdataimporttable',
            name='contract_description',
            field=models.CharField(max_length=1500, null=True, verbose_name='Award value'),
        ),
        migrations.AlterField(
            model_name='tempdataimporttable',
            name='contract_id',
            field=models.CharField(max_length=1500, null=True, verbose_name='Contract Id'),
        ),
        migrations.AlterField(
            model_name='tempdataimporttable',
            name='contract_status',
            field=models.CharField(max_length=1500, null=True, verbose_name='Contract Status'),
        ),
        migrations.AlterField(
            model_name='tempdataimporttable',
            name='contract_status_code',
            field=models.CharField(max_length=1500, null=True, verbose_name='Contract Status Code'),
        ),
        migrations.AlterField(
            model_name='tempdataimporttable',
            name='contract_title',
            field=models.CharField(max_length=1500, null=True, verbose_name='Contract title'),
        ),
        migrations.AlterField(
            model_name='tempdataimporttable',
            name='contract_value',
            field=models.CharField(max_length=1500, null=True, verbose_name='Contract value'),
        ),
        migrations.AlterField(
            model_name='tempdataimporttable',
            name='cpv_code_clear',
            field=models.CharField(max_length=1500, null=True, verbose_name='CPV code clear'),
        ),
        migrations.AlterField(
            model_name='tempdataimporttable',
            name='data_source',
            field=models.CharField(max_length=1500, null=True, verbose_name='Data Source'),
        ),
        migrations.AlterField(
            model_name='tempdataimporttable',
            name='goods_services',
            field=models.CharField(max_length=1500, null=True, verbose_name='Goods/Services'),
        ),
        migrations.AlterField(
            model_name='tempdataimporttable',
            name='link_to_contract',
            field=models.CharField(max_length=1500, null=True, verbose_name='Link to Contract'),
        ),
        migrations.AlterField(
            model_name='tempdataimporttable',
            name='link_to_tender',
            field=models.CharField(max_length=1500, null=True, verbose_name='Link to Tender'),
        ),
        migrations.AlterField(
            model_name='tempdataimporttable',
            name='no_of_bidders',
            field=models.CharField(max_length=1500, null=True, verbose_name='No of bidders'),
        ),
        migrations.AlterField(
            model_name='tempdataimporttable',
            name='ppu_including_vat',
            field=models.CharField(max_length=1500, null=True, verbose_name='Price per units including VAT'),
        ),
        migrations.AlterField(
            model_name='tempdataimporttable',
            name='procurement_procedure',
            field=models.CharField(max_length=1500, null=True, verbose_name='Procurement procedure'),
        ),
        migrations.AlterField(
            model_name='tempdataimporttable',
            name='procurement_process',
            field=models.CharField(max_length=1500, null=True, verbose_name='Procurement process'),
        ),
        migrations.AlterField(
            model_name='tempdataimporttable',
            name='quantity_units',
            field=models.CharField(max_length=1500, null=True, verbose_name='Quantity,units'),
        ),
        migrations.AlterField(
            model_name='tempdataimporttable',
            name='supplier',
            field=models.CharField(max_length=1500, null=True, verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='tempdataimporttable',
            name='supplier_address',
            field=models.CharField(max_length=1500, null=True, verbose_name='Supplier Address'),
        ),
        migrations.AlterField(
            model_name='tempdataimporttable',
            name='supplier_id',
            field=models.CharField(max_length=1500, null=True, verbose_name='Supplier ID'),
        ),
        migrations.AlterField(
            model_name='tempdataimporttable',
            name='tender_value',
            field=models.CharField(max_length=1500, null=True, verbose_name='Tender value'),
        ),
    ]
