# Generated by Django 3.1.2 on 2021-02-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0021_covidmonthlyactivecases_death_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
