# Generated by Django 3.1.2 on 2021-02-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("country", "0020_importbatch_tempdataimporttable"),
    ]

    operations = [
        migrations.AddField(
            model_name="covidmonthlyactivecases",
            name="death_count",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="Death count"),
        ),
    ]
