# Generated by Django 3.1.2 on 2021-02-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0021_covidmonthlyactivecases_death_count'),
        ('country', '0021_auto_20210223_0640'),
    ]

    operations = [
    ]
