# Generated by Django 3.1.2 on 2021-02-26 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0022_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equitycategory',
            options={'verbose_name_plural': 'Equity Categories'},
        ),
    ]
