# Generated by Django 3.1.2 on 2021-03-01 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0022_merge_20210226_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equitycategory',
            options={'verbose_name_plural': 'Equity Categories'},
        ),
    ]
