# Generated by Django 3.1.2 on 2021-03-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("country", "0023_auto_20210301_0839"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(default="", editable=False, max_length=100)),
            ],
        ),
    ]
