# Generated by Django 3.1.2 on 2021-03-02 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("country", "0024_topic"),
        ("country", "0023_auto_20210301_0922"),
    ]

    operations = []
