# Generated by Django 3.1.2 on 2021-03-25 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("country", "0027_redflag_implemented"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="temp_table_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenders",
                to="country.tempdataimporttable",
            ),
        ),
    ]
