# Generated by Django 3.1.7 on 2021-03-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0029_auto_20210325_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redflag',
            name='description',
            field=models.CharField(blank=True, db_index=True, help_text='Not used.', max_length=300, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='redflag',
            name='function_name',
            field=models.CharField(blank=True, db_index=True, help_text='This corresponds to a function in the code. Do not edit it unless you are a developer.', max_length=300, null=True, verbose_name='Function'),
        ),
        migrations.AlterField(
            model_name='redflag',
            name='implemented',
            field=models.BooleanField(blank=True, default=False, help_text='Display the red flag. Do not enable unless you know the red flag is implemented.', null=True),
        ),
        migrations.AlterField(
            model_name='redflag',
            name='title',
            field=models.CharField(blank=True, db_index=True, help_text='A short description of the red flag, as shown in the frontend.', max_length=250, null=True, verbose_name='Title'),
        ),
    ]
