# Generated by Django 3.1.7 on 2021-04-13 06:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0031_auto_20210401_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='gdp',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='GDP per capita, $'),
        ),
        migrations.AlterField(
            model_name='country',
            name='healthcare_budget',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Healthcare spending, $ per capita'),
        ),
    ]
