# Generated by Django 3.1.7 on 2021-04-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0031_auto_20210401_0421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='equity_categories',
        ),
        migrations.AddField(
            model_name='tender',
            name='award_value_local',
            field=models.FloatField(blank=True, null=True, verbose_name='Award value local'),
        ),
        migrations.AddField(
            model_name='tender',
            name='award_value_usd',
            field=models.FloatField(blank=True, null=True, verbose_name='Award value USD'),
        ),
        migrations.AddField(
            model_name='tender',
            name='tender_value_local',
            field=models.FloatField(blank=True, null=True, verbose_name='Tender value local'),
        ),
        migrations.AddField(
            model_name='tender',
            name='tender_value_usd',
            field=models.FloatField(blank=True, null=True, verbose_name='Tender value USD'),
        ),
    ]
