# Generated by Django 3.1.7 on 2021-04-16 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0032_auto_20210413_0605'),
        ('country', '0032_auto_20210405_1052'),
    ]

    operations = [
    ]
