# Generated by Django 3.1.7 on 2021-05-05 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0033_merge_20210416_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to='country.country'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='summary',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='country.country'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='summary',
            field=models.JSONField(null=True),
        ),
    ]
