# Generated by Django 3.2.4 on 2021-07-29 07:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0036_goods_buyer_remove'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='covid_active_cases',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Active cases of Covid-19'),
        ),
    ]
