# Generated by Django 3.1.8 on 2021-08-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0038_remove_goodsservices_no_of_bidders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempdataimporttable',
            name='contract_description',
            field=models.TextField(null=True, verbose_name='Contract description'),
        ),
        migrations.AlterField(
            model_name='tempdataimporttable',
            name='contract_title',
            field=models.TextField(null=True, verbose_name='Contract title'),
        ),
        migrations.AlterField(
            model_name='tempdataimporttable',
            name='contract_value',
            field=models.TextField(null=True, verbose_name='Contract value'),
        ),
        migrations.AlterField(
            model_name='tempdataimporttable',
            name='data_source',
            field=models.TextField(null=True, verbose_name='Data Source'),
        ),
        migrations.AlterField(
            model_name='tempdataimporttable',
            name='link_to_contract',
            field=models.TextField(null=True, verbose_name='Link to Contract'),
        ),
        migrations.AlterField(
            model_name='tempdataimporttable',
            name='link_to_tender',
            field=models.TextField(null=True, verbose_name='Link to Tender'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='buyer_address',
            field=models.TextField(blank=True, null=True, verbose_name='Buyer address'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='buyer_id',
            field=models.CharField(max_length=250, null=True, verbose_name='Buyer ID'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_address',
            field=models.TextField(blank=True, null=True, verbose_name='Supplier address'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_id',
            field=models.CharField(max_length=250, null=True, verbose_name='Supplier ID'),
        ),
    ]
