# Generated by Django 3.1.2 on 2020-12-01 10:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0059_apply_collection_ordering"),
        ("wagtaildocs", "0010_document_file_hash"),
        ("country", "0001_initial"),
        ("wagtailimages", "0022_uploadedimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourcesPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("Report", "Report"),
                            ("Policy", "Policy"),
                            ("Guide", "Guide"),
                            ("Tools", "Tools"),
                            ("Training Material", "Training Material"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", wagtail.core.fields.RichTextField()),
                ("link", models.URLField(max_length=100)),
                ("published_date", models.DateField(verbose_name="Published date")),
                ("author", models.CharField(blank=True, max_length=250)),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="country.country",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtaildocs.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource",
                "verbose_name_plural": "Resources",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="InsightsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("contents_type", models.CharField(choices=[("News", "News"), ("Blog", "Blog")], max_length=20)),
                (
                    "published_date",
                    models.DateField(default=django.utils.timezone.now, editable=False, verbose_name="Published date"),
                ),
                ("body", wagtail.core.fields.RichTextField()),
                ("author", models.CharField(blank=True, max_length=250)),
                (
                    "content_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="country.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Insight",
                "verbose_name_plural": "Insights",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="EventsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("description", wagtail.core.fields.RichTextField()),
                ("event_date", models.DateField(verbose_name="Event date")),
                ("time_from", models.TimeField(verbose_name="Start time")),
                ("time_to", models.TimeField(blank=True, null=True, verbose_name="End time")),
                ("location", models.CharField(max_length=100)),
                (
                    "event_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
            bases=("wagtailcore.page",),
        ),
    ]
