# Generated by Django 3.1.2 on 2020-12-23 11:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0059_apply_collection_ordering"),
        ("wagtailforms", "0004_add_verbose_name_plural"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wagtailredirects", "0006_redirect_increase_max_length"),
        ("content", "0006_delete_homepage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Collection",
            new_name="Contents",
        ),
    ]
