# Generated by Django 3.1.2 on 2021-01-05 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0010_countrypartner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="countrypartner",
            options={"verbose_name_plural": "Country Partners"},
        ),
    ]
