# Generated by Django 3.1.2 on 2021-01-05 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0011_auto_20210105_0601"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CountryPartner",
        ),
    ]
