# Generated by Django 3.1.2 on 2021-01-05 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0012_delete_countrypartner"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryPartner",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-zA-Z ]+$", "Only letters and spaces are allowed in the Country Name"
                            )
                        ],
                        verbose_name="Name",
                    ),
                ),
                ("description", models.CharField(max_length=50, unique=True, verbose_name="Name")),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("website", models.URLField()),
                ("logo", models.ImageField(upload_to=None)),
            ],
            options={
                "verbose_name_plural": "Country Partners",
            },
        ),
    ]
