# Generated by Django 3.1.2 on 2021-01-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_auto_20210105_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrypartner',
            name='description',
            field=models.CharField(max_length=50, unique=True, verbose_name='Description'),
        ),
    ]
