# Generated by Django 3.1.2 on 2021-01-05 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("country", "0015_delete_countrypartner"),
        ("content", "0015_auto_20210105_0713"),
    ]

    operations = [
        migrations.AddField(
            model_name="countrypartner",
            name="country",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="country.country"),
        ),
        migrations.AddField(
            model_name="countrypartner",
            name="order",
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
