# Generated by Django 3.1.2 on 2021-01-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0019_auto_20210115_1135"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staticpage",
            name="page_type",
            field=models.CharField(
                choices=[
                    ("About Us", "About Us"),
                    ("Privacy Policy", "Privacy Policy"),
                    ("Terms Of Use", "Terms Of Use"),
                ],
                max_length=20,
            ),
        ),
    ]
