# Generated by Django 3.1.2 on 2021-01-26 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0018_auto_20210119_1121'),
        ('content', '0026_auto_20210126_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataimport',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='country.country'),
            preserve_default=False,
        ),
    ]
