# Generated by Django 3.1.2 on 2021-01-29 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_auto_20210126_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='insightspage',
            name='news_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='News published date'),
        ),
    ]
