# Generated by Django 3.1.2 on 2021-01-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_insightspage_news_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcespage',
            name='language',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='resourcespage',
            name='topic',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='resourcespage',
            name='link',
            field=models.URLField(max_length=10000),
        ),
    ]
