# Generated by Django 3.1.2 on 2021-02-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0033_auto_20210129_0746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventspage',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Event'},
        ),
        migrations.AlterModelOptions(
            name='insightspage',
            options={'verbose_name': 'News & Blog', 'verbose_name_plural': 'News &  Blog'},
        ),
        migrations.AlterModelOptions(
            name='resourcespage',
            options={'verbose_name': 'Library', 'verbose_name_plural': 'Library'},
        ),
        migrations.AlterModelOptions(
            name='staticpage',
            options={'verbose_name': 'Static Page', 'verbose_name_plural': 'Static Page'},
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='show_in_footer_menu',
            field=models.CharField(blank=True, choices=[('Yes', True), ('No', False)], default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='show_in_header_menu',
            field=models.CharField(blank=True, choices=[('Yes', True), ('No', False)], default=False, max_length=20, null=True),
        ),
    ]
