# Generated by Django 3.1.2 on 2021-02-01 10:25

import content.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('content', '0033_auto_20210129_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataimport',
            name='import_file',
            field=models.ForeignKey(help_text='Only upload xlsx, xls format', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', validators=[content.validators.validate_file_extension]),
        ),
    ]
