# Generated by Django 3.1.2 on 2021-02-01 10:39

import content.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0034_auto_20210201_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimport',
            name='test_file',
            field=models.FileField(null=True, upload_to='documents/%Y/%m/%d', validators=[content.validators.validate_file_extension]),
        ),
    ]
