# Generated by Django 3.1.2 on 2021-02-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0035_auto_20210212_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='show_in_footer_menu',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('Yes', 'No')], default='No', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='show_in_header_menu',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('Yes', 'No')], default='No', max_length=20, null=True),
        ),
    ]
