# Generated by Django 3.1.2 on 2021-02-01 10:46

import content.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0035_dataimport_test_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataimport',
            name='test_file',
        ),
        migrations.AlterField(
            model_name='dataimport',
            name='import_file',
            field=models.FileField(null=True, upload_to='media/documents/', validators=[content.validators.validate_file_extension]),
        ),
    ]
