# Generated by Django 3.1.2 on 2021-02-12 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_auto_20210212_1012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataimport',
            options={'verbose_name': 'Data Imports', 'verbose_name_plural': 'Data Imports'},
        ),
    ]
