# Generated by Django 3.1.2 on 2021-02-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_staticpage_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticpage',
            name='page_type',
        ),
    ]
