# Generated by Django 3.1.2 on 2021-03-01 09:22

import content.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0037_remove_staticpage_page_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimport',
            name='imported',
            field=models.BooleanField(default=False,blank=True),
        ),
    ]
