# Generated by Django 3.1.2 on 2021-02-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0037_auto_20210201_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimport',
            name='validated',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
