# Generated by Django 3.1.2 on 2021-02-26 06:33

import content.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0023_auto_20210226_0633'),
        ('content', '0037_remove_staticpage_page_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='insightspage',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='country.language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insightspage',
            name='topics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.topic'),
        ),
        migrations.AddField(
            model_name='resourcespage',
            name='topics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.topic'),
        ),
    ]
