# Generated by Django 3.1.2 on 2021-03-02 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0038_auto_20210301_1108"),
        ("content", "0038_auto_20210301_0922"),
    ]

    operations = []
