# Generated by Django 3.1.2 on 2021-02-02 06:32

import content.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0038_dataimport_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataimport',
            name='import_file',
            field=models.FileField(null=True, upload_to='documents', validators=[content.validators.validate_file_extension]),
        ),
    ]
