# Generated by Django 3.1.2 on 2021-02-26 08:43

import content.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0023_auto_20210226_0633'),
        ('content', '0038_auto_20210226_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insightspage',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='country.country'),
        ),
    ]
