# Generated by Django 3.1.2 on 2021-02-26 09:39

import content.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0039_auto_20210226_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insightspage',
            name='featured',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20),
        ),
        migrations.AlterField(
            model_name='insightspage',
            name='news_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Published date'),
        ),
        migrations.AlterField(
            model_name='resourcespage',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='country.language'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='show_in_footer_menu',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='show_in_header_menu',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20),
        ),
    ]
