# Generated by Django 3.1.2 on 2021-03-09 10:50

import content.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("country", "0026_dataprovider"),
        ("content", "0040_auto_20210303_1120"),
    ]

    operations = [
        migrations.AddField(
            model_name="staticpage",
            name="country",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="country.country",
            ),
        ),
    ]
