# Generated by Django 3.1.2 on 2021-03-10 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0042_auto_20210310_0737'),
        ('content', '0042_auto_20210310_0749'),
    ]

    operations = [
    ]
