# Generated by Django 3.1.2 on 2021-03-16 10:49

import content.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0043_merge_20210310_1153"),
    ]

    operations = [
        migrations.AddField(
            model_name="staticpage",
            name="static_content_type",
            field=models.CharField(
                choices=[("static_page", "Static Page"), ("methodology", "Methodology")],
                max_length=100,
                null=True,
                verbose_name="Content Type",
            ),
        ),
    ]
