# Generated by Django 3.1.7 on 2021-04-01 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0030_auto_20210331_1526'),
        ('content', '0045_auto_20210331_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataimport',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='country.country'),
        ),
        migrations.AlterField(
            model_name='insightspage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='country.language'),
        ),
        migrations.AlterField(
            model_name='insightspage',
            name='topics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.topic'),
        ),
        migrations.AlterField(
            model_name='resourcespage',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='country.language'),
        ),
        migrations.AlterField(
            model_name='resourcespage',
            name='topics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.topic'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='country.language'),
        ),
    ]
