# Generated by Django 3.1.7 on 2021-04-05 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0046_auto_20210401_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcespage',
            name='language',
        ),
        migrations.RemoveField(
            model_name='resourcespage',
            name='topic',
        ),
    ]