# Generated by Django 3.1.7 on 2021-04-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0046_auto_20210401_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataimport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
