# Generated by Django 3.1.7 on 2021-04-16 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0047_auto_20210415_0910'),
        ('content', '0047_auto_20210405_1123'),
    ]

    operations = [
    ]
