# Generated by Django 3.1.7 on 2021-05-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0048_merge_20210416_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insightspage',
            name='featured',
            field=models.CharField(choices=[(True, 'Yes'), (False, 'No')], default=False, max_length=15, verbose_name='Featured ?'),
        ),
    ]
