# Generated by Django 3.1.8 on 2021-07-26 08:58

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0050_auto_20210503_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimport',
            name='validation',
            field=models.JSONField(default=content.models.default_validation_json),
        ),
        migrations.AddField(
            model_name='dataimport',
            name='import_details',
            field=models.JSONField(default=content.models.default_validation_json),
        ),
    ]
